# default config.yaml
backend: mcp
language: ""
thread_pool_max_workers: 32
ray_max_workers: 1

mcp:
  transport: sse
  host: "0.0.0.0"
  port: 8002

http:
  host: "0.0.0.0"
  port: 8002
  timeout_keep_alive: 600
  limit_concurrency: 64

flow:
  retrieve_task_memory:
    flow_content: build_query_op >> recall_vector_store_op >> rerank_memory_op >> rewrite_memory_op
    description: "Retrieve the most relevant top_k memory experience from historical memory based on the query to help solve tasks better now"
    input_schema:
      query:
        type: "str"
        description: "user query"
        required: true

  summary_task_memory:
    flow_content: trajectory_preprocess_op >> (success_extraction_op|failure_extraction_op|comparative_extraction_op) >> memory_validation_op >> update_vector_store_op
    description: "Summarize trajectories or messages into memories"
    input_schema:
      trajectories:
        type: "list"
        description: "A list of conversation trajectory information, including message content and score. This field does not need to be filled in, the system will complete it automatically."
        required: false

  retrieve_task_memory_simple:
    flow_content: build_query_op >> recall_vector_store_op >> merge_memory_op
    description: "Retrieve the most relevant top_k memory experience from historical memory based on the query to help solve tasks better now"
    input_schema:
      query:
        type: "str"
        description: "current query"
        required: true

  summary_task_memory_simple:
    flow_content: simple_summary_op >> update_vector_store_op
    description: "Summarize trajectories or messages into memories"
    input_schema:
      trajectories:
        type: "list"
        description: "A list of conversation trajectory information, including message content and score. This field does not need to be filled in, the system will complete it automatically."
        required: false

  vector_store:
    flow_content: vector_store_action_op
    description: "directly operate the vector store."
    input_schema:
      action:
        type: "str"
        description: "vector store operations"
        required: true
        enum: [ copy, delete, delete_ids, dump, load ]

  retrieve_personal_memory:
    flow_content: set_query_op >> (extract_time_op | (retrieve_memory_op >> semantic_rank_op)) >> fuse_rerank_op
    description: "Retrieve the most relevant memories from historical memory based on the query to help answer better now."
    input_schema:
      query:
        type: "str"
        description: "user query"
        required: true

  consolidate_personal_memory:
    flow_content: info_filter_op >> (get_observation_op | get_observation_with_time_op | load_today_memory_op) >> contra_repeat_op >> update_vector_store_op
    description: "summary user's observation memory"
    input_schema:
      messages:
        type: "list"
        description: "A list of conversation messages information. This field does not need to be filled in, the system will complete it automatically."
        required: false

#  reconsolidate_personal_memory:
#    flow_content: load_not_reflected_memory_op >> get_reflection_subject_op >> update_insight_op >> long_contra_repeat_op >> update_vector_store_op
#    description: "Consolidate personal memories by generating topic insights, updating values, resolving conflicts, and updating vector store"


llm:
  default:
    backend: openai_compatible
    model_name: qwen3-30b-a3b-thinking-2507
    params:
      temperature: 0.6

embedding_model:
  default:
    backend: openai_compatible
    model_name: text-embedding-v4
    params:
      dimensions: 1024

vector_store:
  default:
    backend: elasticsearch
    embedding_model: default
    params:
      # hosts: "http://localhost:9200"
      hosts: "http://11.160.132.46:8200"
