# default config.yaml
backend: mcp
language: ""
thread_pool_max_workers: 32
ray_max_workers: 1

mcp:
  transport: sse
  host: "0.0.0.0"
  port: 8002

http:
  host: "0.0.0.0"
  port: 8002
  timeout_keep_alive: 600
  limit_concurrency: 64

flow:
  task_retrieve:
    flow_content: build_query_op->recall_vector_store_op->merge_experience_op
#  task_summarizer: simple_summary_op->update_vector_store_op
#  vector_store: vector_store_action_op
#  agent: react_op

  mock_expression_flow:
    flow_content: mock1_op>>((mock4_op>>mock2_op)|mock5_op)>>(mock3_op|mock6_op)
    description: "mock flow"
    input_schema:
      a:
        type: "str"
        description: "mock attr a"
        required: true
      b:
        type: "str"
        description: "mock attr b"
        required: true

op:
  mock1_op:
    backend: mock1_op
    llm: default
    vector_store: default

llm:
  default:
    backend: openai_compatible
    model_name: qwen3-30b-a3b-thinking-2507
    params:
      temperature: 0.6

  qwen3_30b_instruct:
    backend: openai_compatible
    model_name: qwen3-30b-a3b-instruct-2507

embedding_model:
  default:
    backend: openai_compatible
    model_name: text-embedding-v4
    params:
      dimensions: 1024

vector_store:
  default:
    backend: elasticsearch
    embedding_model: default
    params:
      hosts: "http://localhost:9200"
