"""Constants"""

REME_SERVICE_INFO = "REME_SERVICE_INFO"

REME_DEFAULT_HOST = "127.0.0.1"

REME_DEFAULT_PORT = 2333

# CRUD steps: file IO limits and truncation marker (shared across CRUD steps).
DEFAULT_MAX_BYTES = 50 * 1024
MAX_FILE_READ_BYTES = 200 * 1024 * 1024
TRUNCATION_NOTICE_MARKER = "<<TRUNCATION_NOTICE>>"
